sonar.projectKey=Stock-Market-Analysis
sonar.organization=venkatachala
sonar.sources=api,frontend/src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
